import User from "../model/userModel.mjs";
import bcrypt from "bcrypt";
import { v4 as uuid } from "uuid";

const sessions = {};


export const signupAccount = async (req, res) => {
  const { email, password } = req.body;
  try {
    const existingUser = await User.findOne({ email });
    if (existingUser) {
      res.json({ message: "Email exists" });
    } else {
      const encryptedPassword = await bcrypt.hash(password, 10);
      const newUser = new User({
        email,
        password: encryptedPassword,
      });
      await newUser.save();
      // await User.create({ email, password: encryptedPassword });
      res.status(200).json({ message: "Account successfully created" });
    }
  } catch (error) {
    res.json({ error: error.message });
  }
};

export const loginAccount = async (req, res) => {
  const { email, password } = req.body;
  try {
    const existingUser = await User.findOne({ email });
    if (existingUser) {
      const encyptedPassword = await bcrypt.compare(
        password,
        existingUser.password
      );
      if (encyptedPassword) {
        const sessionId = uuid();
        sessions[sessionId] = { email, userId: existingUser._id };
        //res.set to set-cookie which is the id generated by the uuid and note in object sessions the sessionId holds the email and the useriD
        res.set("Set-Cookie", `session=${sessionId}`);
        res.status(200).json({ message: "account successfully logged in" });
      } else {
        res.json({ message: "Incorrect password" });
      }
    } else {
      res.json({ message: "Email does not exist" });
    }
  } catch (error) {
    res.json({ error: error.message });
  }
};

export const getFoods = (req, res) => {
  //using chaining operator (?.) incase req.header.cookir returns null or undefined
  const sessionId = req.headers.cookie?.split("=")[1];
  const userSession = sessions[sessionId];
  if (!userSession) {
    return res.json({ message: "Invalid session" });
  }
  const userId = userSession.userId;
  res.send({
    title: "So its working hahaha",
    userId,
  });
};
